// services/mockApi.js
export const mockStudents = [
    {
      id: 1,
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      course: 'Math',
      phone: '9876543210',
      address: '123 Main St, New York',
      enrolledDate: '2024-09-01',
      description: 'A passionate learner who enjoys solving math puzzles and participating in Olympiads.',
    },
    {
      id: 2,
      name: 'Bob Smith',
      email: 'bob.smith@example.com',
      course: 'Science',
      phone: '9123456780',
      address: '456 Elm St, California',
      enrolledDate: '2024-08-15',
      description: 'Science enthusiast with a deep interest in chemistry and robotics.',
    },
    {
      id: 3,
      name: 'Catherine Liu',
      email: 'catherine.liu@example.com',
      course: 'English',
      phone: '9234567810',
      address: '789 Pine Rd, Texas',
      enrolledDate: '2024-07-12',
      description: 'Book lover and aspiring writer who enjoys creative storytelling.',
    },
    {
      id: 4,
      name: 'David Kumar',
      email: 'david.kumar@example.com',
      course: 'Math',
      phone: '9873214560',
      address: '67 Rose Ave, New Delhi',
      enrolledDate: '2024-10-05',
      description: 'Top of the class in mathematics with strong logical reasoning skills.',
    },
    {
      id: 5,
      name: 'Emma Watson',
      email: 'emma.watson@example.com',
      course: 'Science',
      phone: '9012345678',
      address: '1010 Oxford St, London',
      enrolledDate: '2024-06-18',
      description: 'Loves biology and is working on a personal research project about plant cells.',
    },
    {
      id: 6,
      name: 'Frank Lopez',
      email: 'frank.lopez@example.com',
      course: 'History',
      phone: '9087654321',
      address: '22 Lakeview Dr, Miami',
      enrolledDate: '2024-11-23',
      description: 'History buff who’s especially interested in World War II events.',
    },
    {
      id: 7,
      name: 'Grace Lee',
      email: 'grace.lee@example.com',
      course: 'English',
      phone: '9345678901',
      address: '3000 Market St, Philadelphia',
      enrolledDate: '2024-09-14',
      description: 'Editor of the school magazine and an avid poet.',
    },
    {
      id: 8,
      name: 'Harry Patel',
      email: 'harry.patel@example.com',
      course: 'Science',
      phone: '9874563210',
      address: '987 City Center, Mumbai',
      enrolledDate: '2024-08-08',
      description: 'Curious about space and astrophysics, aiming to become an astronomer.',
    },
    {
      id: 9,
      name: 'Isabella Brown',
      email: 'isabella.brown@example.com',
      course: 'Math',
      phone: '9098765432',
      address: '40 Ocean Blvd, Sydney',
      enrolledDate: '2024-05-29',
      description: 'Enjoys teaching math to juniors and conducting study sessions.',
    },
    {
      id: 10,
      name: 'Jack Wilson',
      email: 'jack.wilson@example.com',
      course: 'History',
      phone: '9234561234',
      address: '560 Ridge Rd, Chicago',
      enrolledDate: '2024-07-03',
      description: 'Interested in ancient civilizations and archaeology.',
    },
    {
      id: 11,
      name: 'Kavya Sharma',
      email: 'kavya.sharma@example.com',
      course: 'Science',
      phone: '9865321470',
      address: '44 Lotus Ln, Bengaluru',
      enrolledDate: '2024-06-01',
      description: 'Focused on environmental science and climate change awareness.',
    },
    {
      id: 12,
      name: 'Liam Garcia',
      email: 'liam.garcia@example.com',
      course: 'Math',
      phone: '9876543012',
      address: '90 Harbor Rd, Los Angeles',
      enrolledDate: '2024-10-10',
      description: 'Competes in national math competitions and enjoys coding.',
    },
    {
      id: 13,
      name: 'Mia Chen',
      email: 'mia.chen@example.com',
      course: 'English',
      phone: '9123409876',
      address: '78 Rainbow St, Beijing',
      enrolledDate: '2024-05-15',
      description: 'Drama club leader and published a short story collection online.',
    },
    {
      id: 14,
      name: 'Nathan Kim',
      email: 'nathan.kim@example.com',
      course: 'History',
      phone: '9345671230',
      address: '345 Palm Ave, Seoul',
      enrolledDate: '2024-11-01',
      description: 'Enjoys studying political history and participates in debates.',
    },
    {
      id: 15,
      name: 'Olivia Davis',
      email: 'olivia.davis@example.com',
      course: 'Science',
      phone: '9898123456',
      address: '555 Crescent Rd, Toronto',
      enrolledDate: '2024-08-25',
      description: 'Aspiring doctor who volunteers at local health camps.',
    },
    {
      id: 16,
      name: 'Pranav Mehta',
      email: 'pranav.mehta@example.com',
      course: 'English',
      phone: '9812347650',
      address: '80 Cyber City, Gurgaon',
      enrolledDate: '2024-09-20',
      description: 'Enjoys scriptwriting and wants to become a filmmaker.',
    },
    {
      id: 17,
      name: 'Quinn Harper',
      email: 'quinn.harper@example.com',
      course: 'Math',
      phone: '9765432109',
      address: '101 Forest Ln, Denver',
      enrolledDate: '2024-06-30',
      description: 'Math club president and also interested in chess.',
    },
    {
      id: 18,
      name: 'Riya Nair',
      email: 'riya.nair@example.com',
      course: 'Science',
      phone: '9871234567',
      address: '400 Tech Park, Kochi',
      enrolledDate: '2024-07-18',
      description: 'Tech-savvy and loves working on electronics projects.',
    },
    // {
    //   id: 19,
    //   name: 'Samir Roy',
    //   email: 'samir.roy@example.com',
    //   course: 'History',
    //   phone: '9786543210',
    //   address: '999 River Rd, Kolkata',
    //   enrolledDate: '2024-10-02',
    //   description: 'Interested in Indian independence history and freedom fighters.',
    // },
    // {
    //   id: 20,
    //   name: 'Tina George',
    //   email: 'tina.george@example.com',
    //   course: 'English',
    //   phone: '9432109876',
    //   address: '12 Green St, Kochi',
    //   enrolledDate: '2024-08-12',
    //   description: 'Public speaking enthusiast and winner of many elocution contests.',
    // },
  ];
  
  export const fetchStudents = () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(mockStudents);
      }, 1000);
    });
  };
  